apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-frontend
  labels:
    app: student-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-frontend
  template:
    metadata:
      labels:
        app: student-frontend
    spec:
      containers:
        - name: student-frontend
          image: mithreshh/student-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: student-frontend-service
spec:
  type: NodePort
  selector:
    app: student-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
